# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcodedaudio',
            name='split',
            field=models.BooleanField(default=False),
        ),
    ]
