# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcoder', '0002_transcodedaudio_split'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chunkedaudio',
            name='raw',
        ),
        migrations.AddField(
            model_name='chunkedaudio',
            name='transcoded',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transcoder.TranscodedAudio'),
        ),
    ]
