# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcoder', '0003_auto_20170322_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chunkedaudio',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='chunkedaudio',
            name='order',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
