# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcoder', '0004_auto_20170322_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkedaudio',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='chunkedaudio',
            unique_together=set([('transcoded', 'order')]),
        ),
    ]
