# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcoder', '0005_auto_20170322_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcodedaudio',
            name='transcribed',
            field=models.BooleanField(default=False),
        ),
    ]
