# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunkedUpload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chunkedupload',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='chunkedupload',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='chunkedupload',
            name='offset',
        ),
        migrations.RemoveField(
            model_name='chunkedupload',
            name='uniqueIdentifier',
        ),
        migrations.AddField(
            model_name='chunkedupload',
            name='resumableChunkNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='chunkedupload',
            name='resumableChunkSize',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='chunkedupload',
            name='resumableCurrentChunkSize',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='chunkedupload',
            name='resumableFilename',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='chunkedupload',
            name='resumableRelativePath',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='chunkedupload',
            name='resumableTotalChunks',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='chunkedupload',
            name='resumableTotalSize',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='chunkedupload',
            name='resumableType',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='chunkedupload',
            name='file',
            field=models.FileField(max_length=255, upload_to=b'temporary/%Y/%m/%d'),
        ),
    ]
