# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunkedUpload', '0002_auto_20170316_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunkedupload',
            name='resumableIdentifier',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
