# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transcriber', '0001_initial'),
        ('speech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('toneName', models.CharField(max_length=255, null=True)),
                ('categoryName', models.CharField(max_length=255, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_tones', to='speech.Audio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SentenceTone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('toneName', models.CharField(max_length=255, null=True)),
                ('categoryName', models.CharField(max_length=255, null=True)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentence_tones', to='transcriber.Transcription')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
