# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transcriber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('toneName', models.CharField(max_length=255, null=True)),
                ('categoryName', models.CharField(max_length=255, null=True)),
                ('transcription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tones', to='transcriber.Transcription')),
            ],
        ),
    ]
