# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('speech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcription', models.TextField(null=True)),
                ('confidence', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('speech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to='speech.Speech')),
            ],
        ),
    ]
