# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import speech.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to=speech.models.get_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foo', models.CharField(max_length=255)),
            ],
        ),
    ]
