# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 23:20
from __future__ import unicode_literals

import common.formatChecker
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', common.formatChecker.AudioVideoFileField(blank=True, null=True, upload_to=b'raw/%Y/%m/%d')),
                ('transcodedPath', models.CharField(max_length=1000, null=True)),
                ('transcoded', models.BooleanField(default=False)),
                ('transcribed', models.BooleanField(default=False)),
                ('toneAnalyzed', models.BooleanField(default=False)),
                ('documentTranscription', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
