# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to=b'raw/%Y/%m/%d')),
                ('transcodedPath', models.CharField(max_length=1000, null=True)),
                ('transcoded', models.BooleanField(default=False)),
                ('transcribed', models.BooleanField(default=False)),
                ('transcribedSpeech', models.TextField(null=True)),
                ('transcriptionConfidence', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timestamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=1000)),
                ('timestampBegin', models.FloatField(null=True)),
                ('timestampEnd', models.FloatField(null=True)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speech.Audio')),
            ],
        ),
    ]
