# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcription', models.TextField(null=True)),
                ('confidence', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='audio',
            name='transcribedSpeech',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='transcriptionConfidence',
        ),
        migrations.AddField(
            model_name='transcription',
            name='audio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speech.Audio'),
        ),
    ]
