# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkedAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk', models.FileField(upload_to=b'raw/%Y/%m/%d/')),
            ],
        ),
        migrations.AddField(
            model_name='rawaudio',
            name='split',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chunkedaudio',
            name='raw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speech.RawAudio'),
        ),
    ]
