# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='convertedToAudio',
            new_name='transcribed',
        ),
    ]
