# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio',
            field=models.FileField(upload_to=b'raw/%Y/%m/%d'),
        ),
    ]
