# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0002_remove_rawaudio_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='transcribed',
            field=models.BooleanField(default=False),
        ),
    ]
