# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0002_auto_20170313_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='transcoded',
            field=models.BooleanField(default=False),
        ),
    ]
