# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0003_speech_transcribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='toneAnalyzed',
            field=models.BooleanField(default=False),
        ),
    ]
