# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 04:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0003_audio_toneanalyzed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speech.Transcription')),
            ],
        ),
        migrations.RemoveField(
            model_name='timestamp',
            name='audio',
        ),
        migrations.DeleteModel(
            name='Timestamp',
        ),
    ]
