# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0003_audio_transcriptionconfidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timestamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=1000)),
                ('timestamp', models.FloatField()),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speech.Audio')),
            ],
        ),
    ]
