# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0004_auto_20170313_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='tone',
            name='categoryName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tone',
            name='score',
            field=models.DecimalField(decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tone',
            name='toneName',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
