# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0004_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timestamp',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='timestamp',
            name='timestampBegin',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='timestamp',
            name='timestampEnd',
            field=models.FloatField(null=True),
        ),
    ]
